services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=samples_dev_db'
      - 'MYSQL_PASSWORD=Mysql123#@!'
      - 'MYSQL_USER=mysqluser'
      - 'MYSQL_ROOT_PASSWORD=Root123#@!'
      
    ports:
      - '3307:3307'
  app:
    build: .
    ports:
      - "9099:9099"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/samples_dev_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: Mysql123#@!
volumes:
  mysql-data: